# Generated by Django 5.0 on 2023-12-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamCardImage', models.ImageField(upload_to='static/images/team')),
                ('teamCardTitle', models.CharField(max_length=100)),
                ('teamCardFbLink', models.CharField(max_length=100)),
                ('teamCardTwitterLink', models.CharField(max_length=100)),
                ('teamCardInstagramLink', models.CharField(max_length=100)),
            ],
        ),
    ]
