# Generated by Django 5.0 on 2023-12-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectImage', models.ImageField(upload_to='static/images/projects')),
                ('projectTitle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicesCardTitle', models.CharField(max_length=100)),
                ('servicesCardDescription', models.CharField(max_length=300)),
                ('servicesCardImage1', models.ImageField(upload_to='static/images/services')),
                ('servicesCardImage2', models.ImageField(upload_to='static/images/services')),
                ('servicesCardImage3', models.ImageField(upload_to='static/images/services')),
                ('servicesCardImage4', models.ImageField(upload_to='static/images/services')),
            ],
        ),
        migrations.CreateModel(
            name='TestiminoalsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testiminoalsCardImage', models.ImageField(upload_to='static/images/testiminoals')),
                ('testiminoalsCardTitle', models.CharField(max_length=100)),
                ('testiminoalsCardDescription', models.CharField(max_length=300)),
                ('testiminoalsCardDesignation', models.CharField(max_length=100)),
            ],
        ),
    ]
