# Generated by Django 5.0 on 2023-12-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroFeaturedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featuredProjectImage', models.ImageField(upload_to='images/hero/featuredproject/')),
                ('featuredProjectTitle', models.CharField(max_length=100)),
                ('featuredProjectText', models.TextField()),
                ('featuredProjectDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeroModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='images/')),
                ('hero_image1', models.ImageField(upload_to='images/hero/')),
                ('hero_image2', models.ImageField(upload_to='images/hero/')),
                ('hero_image3', models.ImageField(upload_to='images/hero/')),
                ('hero_image4', models.ImageField(upload_to='images/hero/')),
                ('hero_com_image1', models.ImageField(upload_to='images/hero/community/')),
                ('hero_com_image2', models.ImageField(upload_to='images/hero/community/')),
                ('hero_com_image3', models.ImageField(upload_to='images/hero/community/')),
                ('hero_com_image4', models.ImageField(upload_to='images/hero/community/')),
            ],
        ),
        migrations.CreateModel(
            name='HeroWorkList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workTitle', models.CharField(max_length=100)),
                ('workCardImage', models.ImageField(upload_to='images/hero/worklist/')),
                ('workCardTitle', models.CharField(max_length=100)),
                ('workCardText', models.TextField()),
                ('workCardImage2', models.ImageField(upload_to='images/hero/worklist/')),
                ('workCardCount', models.CharField(max_length=100)),
                ('workCardText2', models.TextField()),
            ],
        ),
    ]
