# Generated by Django 5.0 on 2023-12-20 02:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0002_heromodel_herotext_heromodel_herotitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='herofeaturedproject',
            name='featuredTitle',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
