# Generated by Django 5.0 on 2023-12-23 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0003_herofeaturedproject_featuredtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herofeaturedproject',
            name='featuredProjectImage',
            field=models.ImageField(upload_to='static/images/hero/featuredproject/'),
        ),
        migrations.AlterField(
            model_name='heromodel',
            name='hero_com_image1',
            field=models.ImageField(upload_to='static/images/hero/community/'),
        ),
        migrations.AlterField(
            model_name='heromodel',
            name='hero_com_image2',
            field=models.ImageField(upload_to='static/images/hero/community/'),
        ),
        migrations.AlterField(
            model_name='heromodel',
            name='hero_com_image3',
            field=models.ImageField(upload_to='static/images/hero/community/'),
        ),
        migrations.AlterField(
            model_name='heromodel',
            name='hero_com_image4',
            field=models.ImageField(upload_to='static/images/hero/community/'),
        ),
        migrations.AlterField(
            model_name='heromodel',
            name='hero_image1',
            field=models.ImageField(upload_to='static/images/hero/'),
        ),
        migrations.AlterField(
            model_name='heromodel',
            name='hero_image2',
            field=models.ImageField(upload_to='static/images/hero/'),
        ),
        migrations.AlterField(
            model_name='heromodel',
            name='hero_image3',
            field=models.ImageField(upload_to='static/images/hero/'),
        ),
        migrations.AlterField(
            model_name='heromodel',
            name='logo',
            field=models.ImageField(upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='heroworklist',
            name='workCardImage',
            field=models.ImageField(upload_to='static/images/hero/worklist/'),
        ),
        migrations.AlterField(
            model_name='heroworklist',
            name='workCardImage2',
            field=models.ImageField(upload_to='static/images/hero/worklist/'),
        ),
    ]
