# Generated by Django 5.0 on 2023-12-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0004_alter_herofeaturedproject_featuredprojectimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heromodel',
            name='hero_image4',
            field=models.ImageField(upload_to='static/images/hero/'),
        ),
        migrations.AlterField(
            model_name='heromodel',
            name='logo',
            field=models.ImageField(max_length=254, upload_to='static/images/'),
        ),
    ]
